##################################################################################################
# Makefile for building: Big_Sim
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Mar 8 17:04:05 2022
# Modified by Sean Gallogly on Thurs Mar 10 18:33:00 2022
# Project:  Big_Sim.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Big_Sim.pro
##################################################################################################


# ============================== GLOBAL VARIABLES AND OPTIONS ====================================

####### Global Variables

ROOT          = ./


####### Compiler, tools and options

CXX              = g++
CXXFLAGS         = -m64 -pipe -std=c++11 -O3 -g -O2 -Wall  
MODULE_CXX_FLAGS = -m64 -pipe -std=c++11 -O2 -fPIC 
INCPATH          = -I. -Iinclude/Big_Sim -I/usr/local/cuda/include -I$(ROOT)include/CBM_CORE_LIB -I$(ROOT)include/CBM_DATA_LIB \
			       -I$(ROOT)include/CBM_STATE_LIB -I$(ROOT)include/CBM_TOOLS_LIB -I$(ROOT)include/CXX_TOOLS_LIB 
LIBS             = -L/user/local/cuda/lib64 -L/usr/local/cuda/lib64 -L/usr/lib64 -L/opt/cuda/lib64 -lcudart
LINK             = g++
LFLAGS           = -m64 
MODULE_LFLAGS    = -m64 -Wl,-O1 -shared

CHK_DIR_EXISTS   = test -d
MKDIR            = mkdir -p
RMDIR            = rmdir


# ===================================== FILES AND DIRECTORIES =====================================


####### Big Simulation Directories

BIG_SIM_SRC_PATH     = $(ROOT)src/Big_Sim/
BIG_SIM_INCLUDE_PATH = $(ROOT)/include/Big_Sim/
BIG_SIM_OBJ_PATH     = $(ROOT)objs/Big_Sim/


####### Big Simulation Files

BIG_SIM_SOURCES    = $(BIG_SIM_SRC_PATH)control.cpp \
		             $(BIG_SIM_SRC_PATH)main.cpp \
		             $(BIG_SIM_SRC_PATH)setsim.cpp 

BIG_SIM_OBJECTS    = $(BIG_SIM_OBJ_PATH)control.o \
		             $(BIG_SIM_OBJ_PATH)main.o \
		             $(BIG_SIM_OBJ_PATH)setsim.o


####### CBM Core Directories

CBM_CORE_SRC_PATH     = $(ROOT)src/CBM_CORE_LIB/
CBM_CORE_INCLUDE_PATH = $(ROOT)include/CBM_CORE_LIB/
CBM_CORE_OBJ_PATH     = $(ROOT)objs/CBM_CORE_LIB/

####### CBM Core Files

CBM_CORE_SOURCES  = $(CBM_CORE_SRC_PATH)innetmodules/innet.cpp \
			        $(CBM_CORE_SRC_PATH)innetmodules/innetallgrmfgo.cpp \
			        $(CBM_CORE_SRC_PATH)interface/cbmsimcore.cpp \
			        $(CBM_CORE_SRC_PATH)interface/cbmsimx2grgodecouple.cpp \
			        $(CBM_CORE_SRC_PATH)interface/innetinterface.cpp \
			        $(CBM_CORE_SRC_PATH)interface/mzoneinterface.cpp \
			        $(CBM_CORE_SRC_PATH)mzonemodules/mzone.cpp

CBM_CORE_OBJECTS  = $(CBM_CORE_OBJ_PATH)kernels_cuda.o \
                    $(CBM_CORE_OBJ_PATH)innet.o \
                    $(CBM_CORE_OBJ_PATH)innetallgrmfgo.o \
                    $(CBM_CORE_OBJ_PATH)cbmsimcore.o \
                    $(CBM_CORE_OBJ_PATH)cbmsimx2grgodecouple.o \
                    $(CBM_CORE_OBJ_PATH)innetinterface.o \
                    $(CBM_CORE_OBJ_PATH)mzoneinterface.o \
                    $(CBM_CORE_OBJ_PATH)mzone.o


####### CBM Data Directories

CBM_DATA_SRC_PATH     = $(ROOT)src/CBM_DATA_LIB/
CBM_DATA_INCLUDE_PATH = $(ROOT)include/CBM_DATA_LIB/
CBM_DATA_OBJ_PATH     = $(ROOT)objs/CBM_DATA_LIB/

####### CBM Data Files

CBM_DATA_SOURCES  = $(CBM_DATA_SRC_PATH)interfaces/ectrialsdata.cpp \
			        $(CBM_DATA_SRC_PATH)interfaces/ispikeraster.cpp \
			        $(CBM_DATA_SRC_PATH)outdata/eyelidout.cpp \
			        $(CBM_DATA_SRC_PATH)outdata/rawuintdata.cpp \
			        $(CBM_DATA_SRC_PATH)peristimhist/peristimhist.cpp \
			        $(CBM_DATA_SRC_PATH)peristimhist/peristimhistfloat.cpp \
			        $(CBM_DATA_SRC_PATH)spikeraster/spikerasterbitarray.cpp

CBM_DATA_OBJECTS  = $(CBM_DATA_OBJ_PATH)ectrialsdata.o \
                    $(CBM_DATA_OBJ_PATH)ispikeraster.o \
                    $(CBM_DATA_OBJ_PATH)eyelidout.o \
                    $(CBM_DATA_OBJ_PATH)rawuintdata.o \
                    $(CBM_DATA_OBJ_PATH)peristimhist.o \
                    $(CBM_DATA_OBJ_PATH)peristimhistfloat.o \
                    $(CBM_DATA_OBJ_PATH)spikerasterbitarray.o


####### CBM State Directories

CBM_STATE_SRC_PATH     = $(ROOT)src/CBM_STATE_LIB/
CBM_STATE_INCLUDE_PATH = $(ROOT)include/CBM_STATE_LIB/
CBM_STATE_OBJ_PATH     = $(ROOT)objs/CBM_STATE_LIB/

####### CBM State Files

CBM_STATE_SOURCES  = $(CBM_STATE_SRC_PATH)interfaces/cbmstate.cpp \
			         $(CBM_STATE_SRC_PATH)interfaces/cbmstatex2grgodecouple.cpp \
			         $(CBM_STATE_SRC_PATH)interfaces/iactivityparams.cpp \
			         $(CBM_STATE_SRC_PATH)interfaces/iconnectivityparams.cpp \
			         $(CBM_STATE_SRC_PATH)interfaces/iinnetconstate.cpp \
			         $(CBM_STATE_SRC_PATH)interfaces/imzoneactstate.cpp \
			         $(CBM_STATE_SRC_PATH)params/activityparams.cpp \
			         $(CBM_STATE_SRC_PATH)params/connectivityparams.cpp \
			         $(CBM_STATE_SRC_PATH)state/innetactivitystate.cpp \
			         $(CBM_STATE_SRC_PATH)state/innetconnectivitystate.cpp \
			         $(CBM_STATE_SRC_PATH)state/innetconstateggialtcon.cpp \
			         $(CBM_STATE_SRC_PATH)state/mzoneactivitystate.cpp \
			         $(CBM_STATE_SRC_PATH)state/mzoneconnectivitystate.cpp

CBM_STATE_OBJECTS  = $(CBM_STATE_OBJ_PATH)cbmstate.o \
                     $(CBM_STATE_OBJ_PATH)cbmstatex2grgodecouple.o \
                     $(CBM_STATE_OBJ_PATH)iactivityparams.o \
                     $(CBM_STATE_OBJ_PATH)iconnectivityparams.o \
                     $(CBM_STATE_OBJ_PATH)iinnetconstate.o \
                     $(CBM_STATE_OBJ_PATH)imzoneactstate.o \
                     $(CBM_STATE_OBJ_PATH)activityparams.o \
                     $(CBM_STATE_OBJ_PATH)connectivityparams.o \
                     $(CBM_STATE_OBJ_PATH)innetactivitystate.o \
                     $(CBM_STATE_OBJ_PATH)innetconnectivitystate.o \
                     $(CBM_STATE_OBJ_PATH)innetconstateggialtcon.o \
                     $(CBM_STATE_OBJ_PATH)mzoneactivitystate.o \
                     $(CBM_STATE_OBJ_PATH)mzoneconnectivitystate.o


####### CBM Tools Objects Directory

CBM_TOOLS_SRC_PATH     = $(ROOT)src/CBM_TOOLS_LIB/
CBM_TOOLS_INCLUDE_PATH = $(ROOT)include/CBM_TOOLS_LIB/
CBM_TOOLS_OBJ_PATH     = $(ROOT)objs/CBM_TOOLS_LIB/

####### CBM Tools Files

CBM_TOOLS_SOURCES  = $(CBM_TOOLS_SRC_PATH)ecmfpopulation.cpp \
			         $(CBM_TOOLS_SRC_PATH)eyelidintegrator.cpp \
			         $(CBM_TOOLS_SRC_PATH)poissonregencells.cpp

CBM_TOOLS_OBJECTS  = $(CBM_TOOLS_OBJ_PATH)ecmfpopulation.o \
                     $(CBM_TOOLS_OBJ_PATH)eyelidintegrator.o \
                     $(CBM_TOOLS_OBJ_PATH)poissonregencells.o


####### CXX Tools Directories

CXX_TOOLS_SRC_PATH     = $(ROOT)src/CXX_TOOLS_LIB/
CXX_TOOLS_INCLUDE_PATH = $(ROOT)include/CXX_TOOLS_LIB/
CXX_TOOLS_OBJ_PATH     = $(ROOT)objs/CXX_TOOLS_LIB/

####### CXX Tools Files

CXX_TOOLS_SOURCES  = $(CXX_TOOLS_SRC_PATH)fileIO/rawbytesrw.cpp \
			         $(CXX_TOOLS_SRC_PATH)memoryMgmt/arrayvalidate.cpp \
			         $(CXX_TOOLS_SRC_PATH)memoryMgmt/dynamic2darray.cpp \
			         $(CXX_TOOLS_SRC_PATH)randGenerators/mersenne.cpp \
			         $(CXX_TOOLS_SRC_PATH)randGenerators/mother.cpp \
			         $(CXX_TOOLS_SRC_PATH)randGenerators/sfmt.cpp

CXX_TOOLS_OBJECTS  = $(CXX_TOOLS_OBJ_PATH)rawbytesrw.o \
                     $(CXX_TOOLS_OBJ_PATH)arrayvalidate.o \
                     $(CXX_TOOLS_OBJ_PATH)dynamic2darray.o \
                     $(CXX_TOOLS_OBJ_PATH)mersenne.o \
                     $(CXX_TOOLS_OBJ_PATH)mother.o \
                     $(CXX_TOOLS_OBJ_PATH)sfmt.o


####### All Module Include Paths

MODULE_OBJ_PATHS = $(CBM_CORE_OBJ_PATH) $(CBM_DATA_OBJ_PATH) $(CBM_STATE_OBJ_PATH) \
					   $(CBM_TOOLS_OBJ_PATH) $(CXX_TOOLS_OBJ_PATH)

####### Module Object Files

MODULE_OBJECTS = $(CBM_CORE_OBJECTS) $(CBM_DATA_OBJECTS) $(CBM_STATE_OBJECTS) \
				 $(CBM_TOOLS_OBJECTS) $(CXX_TOOLS_OBJECTS)


# ================================= COMPILE AND LINK ALL =========================================


####### Target Name

TARGET = $(ROOT)Big_Sim

####### Check or create all object directories

first: $(MODULE_OBJ_PATHS) $(BIG_SIM_OBJ_PATH) finally

finally: all

####### Big Simulation Build rules

$(BIG_SIM_OBJ_PATH):
	@$(CHK_DIR_EXISTS) $(BIG_SIM_OBJ_PATH) || $(MKDIR) $(BIG_SIM_OBJ_PATH)

all: $(TARGET)

$(TARGET):  $(MODULE_OBJECTS) $(BIG_SIM_OBJECTS) 	
	$(LINK) $(LFLAGS) $(INCPATH) -o $(TARGET) $(MODULE_OBJECTS) $(BIG_SIM_OBJECTS) $(LIBS) 
	
####### Compile Big Simulation

$(BIG_SIM_OBJ_PATH)control.o: $(BIG_SIM_SRC_PATH)control.cpp $(BIG_SIM_INCLUDE_PATH)control.h \
		$(BIG_SIM_INCLUDE_PATH)setsim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(BIG_SIM_OBJ_PATH)control.o $(BIG_SIM_SRC_PATH)control.cpp

$(BIG_SIM_OBJ_PATH)main.o: $(BIG_SIM_SRC_PATH)main.cpp $(BIG_SIM_INCLUDE_PATH)control.h \
		$(BIG_SIM_INCLUDE_PATH)setsim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(BIG_SIM_OBJ_PATH)main.o $(BIG_SIM_SRC_PATH)main.cpp

$(BIG_SIM_OBJ_PATH)setsim.o: $(BIG_SIM_SRC_PATH)setsim.cpp $(BIG_SIM_INCLUDE_PATH)setsim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(BIG_SIM_OBJ_PATH)setsim.o $(BIG_SIM_SRC_PATH)setsim.cpp


# ====================================== COMPILE MODULES =========================================


####### CBM Core Compiler Options

CBM_CORE_INCLUDES = -I. -I/usr/local/cuda/include -I/opt/cuda/include -I$(CBM_CORE_INCLUDE_PATH) \
					-I$(CBM_STATE_INCLUDE_PATH) -I$(CXX_TOOLS_INCLUDE_PATH) 

####### CBM Core Build Rules

$(CBM_CORE_OBJ_PATH):
	@$(CHK_DIR_EXISTS) $(CBM_CORE_OBJ_PATH) || $(MKDIR) $(CBM_CORE_OBJ_PATH)

####### Compile CBM Core Cuda Sources 

compiler_cuda_make_all: $(CBM_CORE_OBJ_PATH)kernels_cuda.o

$(CBM_CORE_OBJ_PATH)kernels_cuda.o: $(CBM_CORE_INCLUDE_PATH)cuda/kernels.h \
		$(CBM_CORE_SRC_PATH)cuda/kernels.cu \
		$(CBM_CORE_SRC_PATH)cuda/kernels.cu \
		/usr/include/stdc-predef.h \
		/usr/include/cuda_runtime.h \
		/usr/include/crt/host_config.h \
		/usr/include/features.h \
		/usr/include/x86_64-linux-gnu/sys/cdefs.h \
		/usr/include/x86_64-linux-gnu/bits/wordsize.h \
		/usr/include/x86_64-linux-gnu/bits/long-double.h \
		/usr/include/x86_64-linux-gnu/gnu/stubs.h \
		/usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/lib/gcc/x86_64-linux-gnu/8/include/limits.h \
		/usr/lib/gcc/x86_64-linux-gnu/8/include/syslimits.h \
		/usr/include/limits.h \
		/usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
		/usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
		/usr/include/x86_64-linux-gnu/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
		/usr/include/x86_64-linux-gnu/bits/xopen_lim.h \
		/usr/include/x86_64-linux-gnu/bits/uio_lim.h \
		/usr/lib/gcc/x86_64-linux-gnu/8/include/stddef.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/library_types.h \
		/usr/include/channel_descriptor.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/driver_functions.h \
		/usr/include/vector_functions.h \
		/usr/include/vector_functions.hpp \
		/usr/include/crt/common_functions.h \
		/usr/include/string.h \
		/usr/include/x86_64-linux-gnu/bits/types/locale_t.h \
		/usr/include/x86_64-linux-gnu/bits/types/__locale_t.h \
		/usr/include/strings.h \
		/usr/include/x86_64-linux-gnu/bits/strings_fortified.h \
		/usr/include/x86_64-linux-gnu/bits/string_fortified.h \
		/usr/include/time.h \
		/usr/include/x86_64-linux-gnu/bits/time.h \
		/usr/include/x86_64-linux-gnu/bits/types.h \
		/usr/include/x86_64-linux-gnu/bits/timesize.h \
		/usr/include/x86_64-linux-gnu/bits/typesizes.h \
		/usr/include/x86_64-linux-gnu/bits/time64.h \
		/usr/include/x86_64-linux-gnu/bits/timex.h \
		/usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
		/usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
		/usr/include/x86_64-linux-gnu/bits/types/time_t.h \
		/usr/include/x86_64-linux-gnu/bits/types/struct_tm.h \
		/usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
		/usr/include/x86_64-linux-gnu/bits/endian.h \
		/usr/include/x86_64-linux-gnu/bits/endianness.h \
		/usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
		/usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
		/usr/include/x86_64-linux-gnu/bits/types/struct_itimerspec.h \
		/usr/include/c++/8/new \
		/usr/include/x86_64-linux-gnu/c++/8/bits/c++config.h \
		/usr/include/x86_64-linux-gnu/c++/8/bits/os_defines.h \
		/usr/include/x86_64-linux-gnu/c++/8/bits/cpu_defines.h \
		/usr/include/c++/8/exception \
		/usr/include/c++/8/bits/exception.h \
		/usr/include/c++/8/bits/exception_ptr.h \
		/usr/include/c++/8/bits/exception_defines.h \
		/usr/include/c++/8/bits/cxxabi_init_exception.h \
		/usr/include/c++/8/typeinfo \
		/usr/include/c++/8/bits/hash_bytes.h \
		/usr/include/c++/8/bits/nested_exception.h \
		/usr/include/c++/8/bits/move.h \
		/usr/include/c++/8/bits/concept_check.h \
		/usr/include/c++/8/type_traits \
		/usr/include/stdio.h \
		/usr/lib/gcc/x86_64-linux-gnu/8/include/stdarg.h \
		/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h \
		/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h \
		/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h \
		/usr/include/x86_64-linux-gnu/bits/types/__FILE.h \
		/usr/include/x86_64-linux-gnu/bits/types/FILE.h \
		/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h \
		/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h \
		/usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
		/usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
		/usr/include/x86_64-linux-gnu/bits/stdio.h \
		/usr/include/x86_64-linux-gnu/bits/stdio2.h \
		/usr/include/c++/8/stdlib.h \
		/usr/include/c++/8/cstdlib \
		/usr/include/stdlib.h \
		/usr/include/x86_64-linux-gnu/bits/waitflags.h \
		/usr/include/x86_64-linux-gnu/bits/waitstatus.h \
		/usr/include/x86_64-linux-gnu/bits/floatn.h \
		/usr/include/x86_64-linux-gnu/bits/floatn-common.h \
		/usr/include/x86_64-linux-gnu/sys/types.h \
		/usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
		/usr/include/endian.h \
		/usr/include/x86_64-linux-gnu/bits/byteswap.h \
		/usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
		/usr/include/x86_64-linux-gnu/sys/select.h \
		/usr/include/x86_64-linux-gnu/bits/select.h \
		/usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
		/usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
		/usr/include/x86_64-linux-gnu/bits/select2.h \
		/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
		/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
		/usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
		/usr/include/x86_64-linux-gnu/bits/struct_mutex.h \
		/usr/include/x86_64-linux-gnu/bits/struct_rwlock.h \
		/usr/include/alloca.h \
		/usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h \
		/usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
		/usr/include/x86_64-linux-gnu/bits/stdlib.h \
		/usr/include/c++/8/bits/std_abs.h \
		/usr/include/assert.h \
		/usr/include/crt/math_functions.h \
		/usr/include/c++/8/math.h \
		/usr/include/c++/8/cmath \
		/usr/include/c++/8/bits/cpp_type_traits.h \
		/usr/include/c++/8/ext/type_traits.h \
		/usr/include/math.h \
		/usr/include/x86_64-linux-gnu/bits/math-vector.h \
		/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h \
		/usr/include/x86_64-linux-gnu/bits/flt-eval-method.h \
		/usr/include/x86_64-linux-gnu/bits/fp-logb.h \
		/usr/include/x86_64-linux-gnu/bits/fp-fast.h \
		/usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h \
		/usr/include/x86_64-linux-gnu/bits/mathcalls.h \
		/usr/include/x86_64-linux-gnu/bits/mathcalls-narrow.h \
		/usr/include/x86_64-linux-gnu/bits/iscanonical.h \
		/usr/include/x86_64-linux-gnu/bits/mathinline.h \
		/usr/include/crt/math_functions.hpp \
		/usr/include/cuda_surface_types.h \
		/usr/include/cuda_texture_types.h \
		/usr/include/crt/device_functions.h \
		/usr/include/crt/device_functions.hpp \
		/usr/include/device_atomic_functions.h \
		/usr/include/device_atomic_functions.hpp \
		/usr/include/crt/device_double_functions.h \
		/usr/include/crt/device_double_functions.hpp \
		/usr/include/sm_20_atomic_functions.h \
		/usr/include/sm_20_atomic_functions.hpp \
		/usr/include/sm_32_atomic_functions.h \
		/usr/include/sm_32_atomic_functions.hpp \
		/usr/include/sm_35_atomic_functions.h \
		/usr/include/sm_60_atomic_functions.h \
		/usr/include/sm_60_atomic_functions.hpp \
		/usr/include/sm_20_intrinsics.h \
		/usr/include/sm_20_intrinsics.hpp \
		/usr/include/sm_30_intrinsics.h \
		/usr/include/sm_30_intrinsics.hpp \
		/usr/include/sm_32_intrinsics.h \
		/usr/include/sm_32_intrinsics.hpp \
		/usr/include/sm_35_intrinsics.h \
		/usr/include/sm_61_intrinsics.h \
		/usr/include/sm_61_intrinsics.hpp \
		/usr/include/crt/sm_70_rt.h \
		/usr/include/crt/sm_70_rt.hpp \
		/usr/include/surface_functions.h \
		/usr/include/texture_fetch_functions.h \
		/usr/include/texture_indirect_functions.h \
		/usr/include/surface_indirect_functions.h \
		/usr/include/device_launch_parameters.h \
		$(CBM_CORE_INCLUDE_PATH)cuda/kernels.h \
		/usr/include/cuda.h \
		/usr/lib/gcc/x86_64-linux-gnu/8/include/stdint.h \
		/usr/include/stdint.h \
		/usr/include/x86_64-linux-gnu/bits/wchar.h \
		/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
		/usr/include/device_functions.h \
		/usr/include/c++/8/iostream \
		/usr/include/c++/8/ostream \
		/usr/include/c++/8/ios \
		/usr/include/c++/8/iosfwd \
		/usr/include/c++/8/bits/stringfwd.h \
		/usr/include/c++/8/bits/memoryfwd.h \
		/usr/include/c++/8/bits/postypes.h \
		/usr/include/c++/8/cwchar \
		/usr/include/wchar.h \
		/usr/include/x86_64-linux-gnu/bits/types/wint_t.h \
		/usr/include/x86_64-linux-gnu/bits/types/mbstate_t.h \
		/usr/include/x86_64-linux-gnu/bits/wchar2.h \
		/usr/include/c++/8/bits/char_traits.h \
		/usr/include/c++/8/bits/stl_algobase.h \
		/usr/include/c++/8/bits/functexcept.h \
		/usr/include/c++/8/ext/numeric_traits.h \
		/usr/include/c++/8/bits/stl_pair.h \
		/usr/include/c++/8/bits/stl_iterator_base_types.h \
		/usr/include/c++/8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/8/debug/assertions.h \
		/usr/include/c++/8/bits/stl_iterator.h \
		/usr/include/c++/8/bits/ptr_traits.h \
		/usr/include/c++/8/debug/debug.h \
		/usr/include/c++/8/bits/predefined_ops.h \
		/usr/include/c++/8/cstdint \
		/usr/include/c++/8/bits/localefwd.h \
		/usr/include/x86_64-linux-gnu/c++/8/bits/c++locale.h \
		/usr/include/c++/8/clocale \
		/usr/include/locale.h \
		/usr/include/x86_64-linux-gnu/bits/locale.h \
		/usr/include/c++/8/cctype \
		/usr/include/ctype.h \
		/usr/include/c++/8/bits/ios_base.h \
		/usr/include/c++/8/ext/atomicity.h \
		/usr/include/x86_64-linux-gnu/c++/8/bits/gthr.h \
		/usr/include/x86_64-linux-gnu/c++/8/bits/gthr-default.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/x86_64-linux-gnu/bits/sched.h \
		/usr/include/x86_64-linux-gnu/bits/types/struct_sched_param.h \
		/usr/include/x86_64-linux-gnu/bits/cpu-set.h \
		/usr/include/x86_64-linux-gnu/bits/setjmp.h \
		/usr/include/x86_64-linux-gnu/c++/8/bits/atomic_word.h \
		/usr/include/c++/8/bits/locale_classes.h \
		/usr/include/c++/8/string \
		/usr/include/c++/8/bits/allocator.h \
		/usr/include/x86_64-linux-gnu/c++/8/bits/c++allocator.h \
		/usr/include/c++/8/ext/new_allocator.h \
		/usr/include/c++/8/bits/ostream_insert.h \
		/usr/include/c++/8/bits/cxxabi_forced.h \
		/usr/include/c++/8/bits/stl_function.h \
		/usr/include/c++/8/backward/binders.h \
		/usr/include/c++/8/bits/range_access.h \
		/usr/include/c++/8/initializer_list \
		/usr/include/c++/8/bits/basic_string.h \
		/usr/include/c++/8/ext/alloc_traits.h \
		/usr/include/c++/8/bits/alloc_traits.h \
		/usr/include/c++/8/ext/string_conversions.h \
		/usr/include/c++/8/cstdio \
		/usr/include/c++/8/cerrno \
		/usr/include/errno.h \
		/usr/include/x86_64-linux-gnu/bits/errno.h \
		/usr/include/linux/errno.h \
		/usr/include/x86_64-linux-gnu/asm/errno.h \
		/usr/include/asm-generic/errno.h \
		/usr/include/asm-generic/errno-base.h \
		/usr/include/x86_64-linux-gnu/bits/types/error_t.h \
		/usr/include/c++/8/bits/functional_hash.h \
		/usr/include/c++/8/bits/basic_string.tcc \
		/usr/include/c++/8/bits/locale_classes.tcc \
		/usr/include/c++/8/system_error \
		/usr/include/x86_64-linux-gnu/c++/8/bits/error_constants.h \
		/usr/include/c++/8/stdexcept \
		/usr/include/c++/8/streambuf \
		/usr/include/c++/8/bits/streambuf.tcc \
		/usr/include/c++/8/bits/basic_ios.h \
		/usr/include/c++/8/bits/locale_facets.h \
		/usr/include/c++/8/cwctype \
		/usr/include/wctype.h \
		/usr/include/x86_64-linux-gnu/bits/wctype-wchar.h \
		/usr/include/x86_64-linux-gnu/c++/8/bits/ctype_base.h \
		/usr/include/c++/8/bits/streambuf_iterator.h \
		/usr/include/x86_64-linux-gnu/c++/8/bits/ctype_inline.h \
		/usr/include/c++/8/bits/locale_facets.tcc \
		/usr/include/c++/8/bits/basic_ios.tcc \
		/usr/include/c++/8/bits/ostream.tcc \
		/usr/include/c++/8/istream \
		/usr/include/c++/8/bits/istream.tcc \
		$(CXX_TOOLS_INCLUDE_PATH)stdDefinitions/pstdint.h \
		/usr/include/crt/host_config.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/library_types.h \
		/usr/include/channel_descriptor.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/driver_functions.h \
		/usr/include/vector_functions.h \
		/usr/include/vector_functions.hpp \
		/usr/include/crt/device_functions.h \
		/usr/include/crt/device_functions.hpp \
		/usr/include/crt/device_double_functions.h \
		/usr/include/crt/device_double_functions.hpp \
		/usr/include/crt/sm_70_rt.h \
		/usr/include/crt/sm_70_rt.hpp \
		/usr/include/crt/common_functions.h \
		/usr/include/crt/math_functions.h \
		/usr/include/crt/math_functions.hpp \
		/usr/include/cuda_surface_types.h \
		/usr/include/cuda_texture_types.h \
		/usr/include/device_launch_parameters.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/crt/host_defines.h \
		/usr/include/vector_types.h \
		/usr/include/crt/host_defines.h \
		/usr/lib/gcc/x86_64-linux-gnu/8/include/syslimits.h \
		/usr/include/driver_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/vector_types.h \
		/usr/include/driver_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/vector_types.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/driver_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/vector_types.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/vector_functions.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/crt/math_functions.h \
		/usr/include/crt/math_functions.hpp \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/crt/math_functions.hpp \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/channel_descriptor.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/channel_descriptor.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/crt/device_functions.hpp \
		/usr/include/crt/device_double_functions.h \
		/usr/include/crt/device_double_functions.hpp \
		/usr/include/crt/sm_70_rt.h \
		/usr/include/crt/sm_70_rt.hpp \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/device_atomic_functions.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/crt/device_double_functions.hpp \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_20_atomic_functions.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_32_atomic_functions.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_32_atomic_functions.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_32_atomic_functions.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_60_atomic_functions.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_20_intrinsics.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_30_intrinsics.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_32_intrinsics.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_32_intrinsics.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_32_intrinsics.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/sm_61_intrinsics.hpp \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/crt/sm_70_rt.hpp \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/cuda_surface_types.h \
		/usr/include/channel_descriptor.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/cuda_texture_types.h \
		/usr/include/channel_descriptor.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/cuda_runtime_api.h \
		/usr/include/crt/host_defines.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/cuda_device_runtime_api.h \
		/usr/include/vector_types.h \
		/usr/include/crt/host_defines.h \
		/usr/lib/gcc/x86_64-linux-gnu/8/include/stdint-gcc.h \
		/usr/include/crt/device_functions.h \
		/usr/include/builtin_types.h \
		/usr/include/device_types.h \
		/usr/include/crt/host_defines.h \
		/usr/include/driver_types.h \
		/usr/include/vector_types.h \
		/usr/include/surface_types.h \
		/usr/include/texture_types.h \
		/usr/include/crt/device_functions.hpp \
		/usr/include/crt/device_double_functions.h \
		/usr/include/crt/device_double_functions.hpp \
		/usr/include/crt/sm_70_rt.h \
		/usr/include/crt/sm_70_rt.hpp
	nvcc -O3 -arch=compute_61 -Xcompiler -fPIC $(CBM_CORE_INCLUDES) -c $(CBM_CORE_SRC_PATH)cuda/kernels.cu -o $(CBM_CORE_OBJ_PATH)kernels_cuda.o

####### compile CBM Core Non-Cuda Sources

$(CBM_CORE_OBJ_PATH)innet.o: $(CBM_CORE_SRC_PATH)innetmodules/innet.cpp $(CBM_CORE_INCLUDE_PATH)innetmodules/innet.h \
                             $(CBM_CORE_INCLUDE_PATH)cuda/kernels.h \
                             $(CBM_CORE_INCLUDE_PATH)interface/innetinterface.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_CORE_INCLUDES) -o $(CBM_CORE_OBJ_PATH)innet.o $(CBM_CORE_SRC_PATH)innetmodules/innet.cpp
 
$(CBM_CORE_OBJ_PATH)innetallgrmfgo.o: $(CBM_CORE_SRC_PATH)innetmodules/innetallgrmfgo.cpp $(CBM_CORE_INCLUDE_PATH)innetmodules/innetallgrmfgo.h \
                                      $(CBM_CORE_INCLUDE_PATH)innetmodules/innet.h \
                                      $(CBM_CORE_INCLUDE_PATH)cuda/kernels.h \
                                      $(CBM_CORE_INCLUDE_PATH)interface/innetinterface.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_CORE_INCLUDES) -o $(CBM_CORE_OBJ_PATH)innetallgrmfgo.o $(CBM_CORE_SRC_PATH)innetmodules/innetallgrmfgo.cpp
 
$(CBM_CORE_OBJ_PATH)cbmsimcore.o: $(CBM_CORE_SRC_PATH)interface/cbmsimcore.cpp $(CBM_CORE_INCLUDE_PATH)interface/cbmsimcore.h \
                                  $(CBM_CORE_INCLUDE_PATH)interface/innetinterface.h \
                                  $(CBM_CORE_INCLUDE_PATH)interface/mzoneinterface.h \
                                  $(CBM_CORE_INCLUDE_PATH)mzonemodules/mzone.h \
                                  $(CBM_CORE_INCLUDE_PATH)cuda/kernels.h \
                                  $(CBM_CORE_INCLUDE_PATH)innetmodules/innet.h \
                                  $(CBM_CORE_INCLUDE_PATH)innetmodules/innetallgrmfgo.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_CORE_INCLUDES) -o $(CBM_CORE_OBJ_PATH)cbmsimcore.o $(CBM_CORE_SRC_PATH)interface/cbmsimcore.cpp
  
$(CBM_CORE_OBJ_PATH)cbmsimx2grgodecouple.o: $(CBM_CORE_SRC_PATH)interface/cbmsimx2grgodecouple.cpp $(CBM_CORE_INCLUDE_PATH)interface/cbmsimx2grgodecouple.h \
                                            $(CBM_CORE_INCLUDE_PATH)interface/innetinterface.h \
                                            $(CBM_CORE_INCLUDE_PATH)interface/mzoneinterface.h \
                                            $(CBM_CORE_INCLUDE_PATH)mzonemodules/mzone.h \
                                            $(CBM_CORE_INCLUDE_PATH)cuda/kernels.h \
                                            $(CBM_CORE_INCLUDE_PATH)innetmodules/innet.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_CORE_INCLUDES) -o $(CBM_CORE_OBJ_PATH)cbmsimx2grgodecouple.o $(CBM_CORE_SRC_PATH)interface/cbmsimx2grgodecouple.cpp
 
$(CBM_CORE_OBJ_PATH)innetinterface.o: $(CBM_CORE_SRC_PATH)interface/innetinterface.cpp $(CBM_CORE_INCLUDE_PATH)interface/innetinterface.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_CORE_INCLUDES) -o $(CBM_CORE_OBJ_PATH)innetinterface.o $(CBM_CORE_SRC_PATH)interface/innetinterface.cpp
  
$(CBM_CORE_OBJ_PATH)mzoneinterface.o: $(CBM_CORE_SRC_PATH)interface/mzoneinterface.cpp $(CBM_CORE_INCLUDE_PATH)interface/mzoneinterface.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_CORE_INCLUDES) -o $(CBM_CORE_OBJ_PATH)mzoneinterface.o $(CBM_CORE_SRC_PATH)interface/mzoneinterface.cpp
  
$(CBM_CORE_OBJ_PATH)mzone.o: $(CBM_CORE_SRC_PATH)mzonemodules/mzone.cpp $(CBM_CORE_INCLUDE_PATH)mzonemodules/mzone.h \
                             $(CBM_CORE_INCLUDE_PATH)cuda/kernels.h \
                             $(CBM_CORE_INCLUDE_PATH)interface/mzoneinterface.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_CORE_INCLUDES) -o $(CBM_CORE_OBJ_PATH)mzone.o $(CBM_CORE_SRC_PATH)mzonemodules/mzone.cpp


####### CBM Data Compiler Options

CBM_DATA_INCLUDES = -I. -I$(BIG_SIM_INCLUDE_PATH) -I$(CBM_DATA_INCLUDE_PATH) -I$(CXX_TOOLS_INCLUDE_PATH) 

####### CBM Data Build Rules

$(CBM_DATA_OBJ_PATH):
	@$(CHK_DIR_EXISTS) $(CBM_DATA_OBJ_PATH) || $(MKDIR) $(CBM_DATA_OBJ_PATH)

####### Compile CBM Data Sources 

$(CBM_DATA_OBJ_PATH)ectrialsdata.o: $(CBM_DATA_SRC_PATH)interfaces/ectrialsdata.cpp $(CBM_DATA_INCLUDE_PATH)interfaces/ectrialsdata.h \
                                    $(CBM_DATA_INCLUDE_PATH)outdata/eyelidout.h \
                                    $(CBM_DATA_INCLUDE_PATH)outdata/rawuintdata.h \
                                    $(CBM_DATA_INCLUDE_PATH)spikeraster/spikerasterbitarray.h \
                                    $(CBM_DATA_INCLUDE_PATH)interfaces/ispikeraster.h \
                                    $(CBM_DATA_INCLUDE_PATH)peristimhist/peristimhist.h \
                                    $(CBM_DATA_INCLUDE_PATH)peristimhist/peristimhistfloat.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_DATA_INCLUDES) -o $(CBM_DATA_OBJ_PATH)ectrialsdata.o $(CBM_DATA_SRC_PATH)interfaces/ectrialsdata.cpp
	
$(CBM_DATA_OBJ_PATH)ispikeraster.o: $(CBM_DATA_SRC_PATH)interfaces/ispikeraster.cpp $(CBM_DATA_INCLUDE_PATH)interfaces/ispikeraster.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_DATA_INCLUDES) -o $(CBM_DATA_OBJ_PATH)ispikeraster.o $(CBM_DATA_SRC_PATH)interfaces/ispikeraster.cpp
  
$(CBM_DATA_OBJ_PATH)eyelidout.o: $(CBM_DATA_SRC_PATH)outdata/eyelidout.cpp $(CBM_DATA_INCLUDE_PATH)outdata/eyelidout.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_DATA_INCLUDES) -o $(CBM_DATA_OBJ_PATH)eyelidout.o $(CBM_DATA_SRC_PATH)outdata/eyelidout.cpp
  
$(CBM_DATA_OBJ_PATH)rawuintdata.o: $(CBM_DATA_SRC_PATH)outdata/rawuintdata.cpp $(CBM_DATA_INCLUDE_PATH)outdata/rawuintdata.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_DATA_INCLUDES) -o $(CBM_DATA_OBJ_PATH)rawuintdata.o $(CBM_DATA_SRC_PATH)outdata/rawuintdata.cpp
  
$(CBM_DATA_OBJ_PATH)peristimhist.o: $(CBM_DATA_SRC_PATH)peristimhist/peristimhist.cpp $(CBM_DATA_INCLUDE_PATH)peristimhist/peristimhist.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_DATA_INCLUDES) -o $(CBM_DATA_OBJ_PATH)peristimhist.o $(CBM_DATA_SRC_PATH)peristimhist/peristimhist.cpp
  
2 $(CBM_DATA_OBJ_PATH)peristimhistfloat.o: $(CBM_DATA_SRC_PATH)peristimhist/peristimhistfloat.cpp $(CBM_DATA_INCLUDE_PATH)peristimhist/peristimhistfloat.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_DATA_INCLUDES) -o $(CBM_DATA_OBJ_PATH)peristimhistfloat.o $(CBM_DATA_SRC_PATH)peristimhist/peristimhistfloat.cpp
  
$(CBM_DATA_OBJ_PATH)spikerasterbitarray.o: $(CBM_DATA_SRC_PATH)spikeraster/spikerasterbitarray.cpp $(CBM_DATA_INCLUDE_PATH)spikeraster/spikerasterbitarray.h \
                                           $(CBM_DATA_INCLUDE_PATH)interfaces/ispikeraster.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_DATA_INCLUDES) -o $(CBM_DATA_OBJ_PATH)spikerasterbitarray.o $(CBM_DATA_SRC_PATH)spikeraster/spikerasterbitarray.cpp


####### CBM State Compiler Options

CBM_STATE_INCLUDES = -I. -I$(CBM_STATE_INCLUDE_PATH) -I$(CXX_TOOLS_INCLUDE_PATH)

####### CBM State Build Rules

$(CBM_STATE_OBJ_PATH):
	@$(CHK_DIR_EXISTS) $(CBM_STATE_OBJ_PATH) || $(MKDIR) $(CBM_STATE_OBJ_PATH)

####### Compile CBM State Sources

$(CBM_STATE_OBJ_PATH)cbmstate.o: $(CBM_STATE_SRC_PATH)interfaces/cbmstate.cpp $(CBM_STATE_INCLUDE_PATH)interfaces/cbmstate.h \
		$(CBM_STATE_INCLUDE_PATH)params/activityparams.h \
		$(CBM_STATE_INCLUDE_PATH)interfaces/iactivityparams.h \
		$(CBM_STATE_INCLUDE_PATH)params/connectivityparams.h \
		$(CBM_STATE_INCLUDE_PATH)interfaces/iconnectivityparams.h \
		$(CBM_STATE_INCLUDE_PATH)state/innetconnectivitystate.h \
		$(CBM_STATE_INCLUDE_PATH)interfaces/iinnetconstate.h \
		$(CBM_STATE_INCLUDE_PATH)state/innetconstateggialtcon.h \
		$(CBM_STATE_INCLUDE_PATH)state/mzoneconnectivitystate.h \
		$(CBM_STATE_INCLUDE_PATH)state/innetactivitystate.h \
		$(CBM_STATE_INCLUDE_PATH)state/mzoneactivitystate.h \
		$(CBM_STATE_INCLUDE_PATH)interfaces/imzoneactstate.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)cbmstate.o $(CBM_STATE_SRC_PATH)interfaces/cbmstate.cpp

$(CBM_STATE_OBJ_PATH)cbmstatex2grgodecouple.o: $(CBM_STATE_SRC_PATH)interfaces/cbmstatex2grgodecouple.cpp $(CBM_STATE_INCLUDE_PATH)interfaces/cbmstatex2grgodecouple.h \
		$(CBM_STATE_INCLUDE_PATH)params/activityparams.h \
		$(CBM_STATE_INCLUDE_PATH)interfaces/iactivityparams.h \
		$(CBM_STATE_INCLUDE_PATH)params/connectivityparams.h \
		$(CBM_STATE_INCLUDE_PATH)interfaces/iconnectivityparams.h \
		$(CBM_STATE_INCLUDE_PATH)state/innetconnectivitystate.h \
		$(CBM_STATE_INCLUDE_PATH)interfaces/iinnetconstate.h \
		$(CBM_STATE_INCLUDE_PATH)state/mzoneconnectivitystate.h \
		$(CBM_STATE_INCLUDE_PATH)state/innetactivitystate.h \
		$(CBM_STATE_INCLUDE_PATH)state/mzoneactivitystate.h \
		$(CBM_STATE_INCLUDE_PATH)interfaces/imzoneactstate.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)cbmstatex2grgodecouple.o $(CBM_STATE_SRC_PATH)interfaces/cbmstatex2grgodecouple.cpp

$(CBM_STATE_OBJ_PATH)iactivityparams.o: $(CBM_STATE_SRC_PATH)interfaces/iactivityparams.cpp $(CBM_STATE_INCLUDE_PATH)interfaces/iactivityparams.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)iactivityparams.o $(CBM_STATE_SRC_PATH)interfaces/iactivityparams.cpp

$(CBM_STATE_OBJ_PATH)iconnectivityparams.o: $(CBM_STATE_SRC_PATH)interfaces/iconnectivityparams.cpp $(CBM_STATE_INCLUDE_PATH)interfaces/iconnectivityparams.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)iconnectivityparams.o $(CBM_STATE_SRC_PATH)interfaces/iconnectivityparams.cpp

$(CBM_STATE_OBJ_PATH)iinnetconstate.o: $(CBM_STATE_SRC_PATH)interfaces/iinnetconstate.cpp $(CBM_STATE_INCLUDE_PATH)interfaces/iinnetconstate.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)iinnetconstate.o $(CBM_STATE_SRC_PATH)interfaces/iinnetconstate.cpp

$(CBM_STATE_OBJ_PATH)imzoneactstate.o: $(CBM_STATE_SRC_PATH)interfaces/imzoneactstate.cpp $(CBM_STATE_INCLUDE_PATH)interfaces/imzoneactstate.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)imzoneactstate.o $(CBM_STATE_SRC_PATH)interfaces/imzoneactstate.cpp

$(CBM_STATE_OBJ_PATH)activityparams.o: $(CBM_STATE_SRC_PATH)params/activityparams.cpp $(CBM_STATE_INCLUDE_PATH)params/activityparams.h \
		                               $(CBM_STATE_INCLUDE_PATH)interfaces/iactivityparams.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)activityparams.o $(CBM_STATE_SRC_PATH)params/activityparams.cpp

$(CBM_STATE_OBJ_PATH)connectivityparams.o: $(CBM_STATE_SRC_PATH)params/connectivityparams.cpp $(CBM_STATE_INCLUDE_PATH)params/connectivityparams.h \
		                                   $(CBM_STATE_INCLUDE_PATH)interfaces/iconnectivityparams.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)connectivityparams.o $(CBM_STATE_SRC_PATH)params/connectivityparams.cpp

$(CBM_STATE_OBJ_PATH)innetactivitystate.o: $(CBM_STATE_SRC_PATH)state/innetactivitystate.cpp $(CBM_STATE_INCLUDE_PATH)state/innetactivitystate.h \
		                                   $(CBM_STATE_INCLUDE_PATH)params/connectivityparams.h \
		                                   $(CBM_STATE_INCLUDE_PATH)interfaces/iconnectivityparams.h \
		                                   $(CBM_STATE_INCLUDE_PATH)params/activityparams.h \
		                                   $(CBM_STATE_INCLUDE_PATH)interfaces/iactivityparams.h \
		                                   $(CBM_STATE_INCLUDE_PATH)state/innetconnectivitystate.h \
		                                   $(CBM_STATE_INCLUDE_PATH)interfaces/iinnetconstate.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)innetactivitystate.o $(CBM_STATE_SRC_PATH)state/innetactivitystate.cpp

$(CBM_STATE_OBJ_PATH)innetconnectivitystate.o: $(CBM_STATE_SRC_PATH)state/innetconnectivitystate.cpp $(CBM_STATE_INCLUDE_PATH)state/innetconnectivitystate.h \
		                                       $(CBM_STATE_INCLUDE_PATH)params/connectivityparams.h \
		                                       $(CBM_STATE_INCLUDE_PATH)interfaces/iconnectivityparams.h \
		                                       $(CBM_STATE_INCLUDE_PATH)interfaces/iinnetconstate.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)innetconnectivitystate.o $(CBM_STATE_SRC_PATH)state/innetconnectivitystate.cpp

$(CBM_STATE_OBJ_PATH)innetconstateggialtcon.o: $(CBM_STATE_SRC_PATH)state/innetconstateggialtcon.cpp $(CBM_STATE_INCLUDE_PATH)state/innetconstateggialtcon.h \
		                                       $(CBM_STATE_INCLUDE_PATH)state/innetconnectivitystate.h \
		                                       $(CBM_STATE_INCLUDE_PATH)params/connectivityparams.h \
		                                       $(CBM_STATE_INCLUDE_PATH)interfaces/iconnectivityparams.h \
		                                       $(CBM_STATE_INCLUDE_PATH)interfaces/iinnetconstate.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)innetconstateggialtcon.o $(CBM_STATE_SRC_PATH)state/innetconstateggialtcon.cpp

$(CBM_STATE_OBJ_PATH)mzoneactivitystate.o: $(CBM_STATE_SRC_PATH)state/mzoneactivitystate.cpp $(CBM_STATE_INCLUDE_PATH)state/mzoneactivitystate.h \
		                                   $(CBM_STATE_INCLUDE_PATH)params/connectivityparams.h \
		                                   $(CBM_STATE_INCLUDE_PATH)interfaces/iconnectivityparams.h \
		                                   $(CBM_STATE_INCLUDE_PATH)params/activityparams.h \
		                                   $(CBM_STATE_INCLUDE_PATH)interfaces/iactivityparams.h \
		                                   $(CBM_STATE_INCLUDE_PATH)interfaces/imzoneactstate.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)mzoneactivitystate.o $(CBM_STATE_SRC_PATH)state/mzoneactivitystate.cpp

$(CBM_STATE_OBJ_PATH)mzoneconnectivitystate.o: $(CBM_STATE_SRC_PATH)state/mzoneconnectivitystate.cpp $(CBM_STATE_INCLUDE_PATH)state/mzoneconnectivitystate.h \
		                                       $(CBM_STATE_INCLUDE_PATH)params/connectivityparams.h \
		                                       $(CBM_STATE_INCLUDE_PATH)interfaces/iconnectivityparams.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_STATE_INCLUDES) -o $(CBM_STATE_OBJ_PATH)mzoneconnectivitystate.o $(CBM_STATE_SRC_PATH)state/mzoneconnectivitystate.cpp


####### CBM Tools Compiler Options

CBM_TOOLS_INCLUDES = -I. -I$(CBM_CORE_INCLUDE_PATH) -I$(CBM_TOOLS_INCLUDE_PATH) -I$(CXX_TOOLS_INCLUDE_PATH)

####### CBM Tools Build Rules

$(CBM_TOOLS_OBJ_PATH):
	@$(CHK_DIR_EXISTS) $(CBM_TOOLS_OBJ_PATH) || $(MKDIR) $(CBM_TOOLS_OBJ_PATH)

####### Compile CBM Tools Sources

$(CBM_TOOLS_OBJ_PATH)ecmfpopulation.o: $(CBM_TOOLS_SRC_PATH)ecmfpopulation.cpp $(CBM_TOOLS_INCLUDE_PATH)/ecmfpopulation.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_TOOLS_INCLUDES) -o $(CBM_TOOLS_OBJ_PATH)ecmfpopulation.o $(CBM_TOOLS_SRC_PATH)ecmfpopulation.cpp

$(CBM_TOOLS_OBJ_PATH)eyelidintegrator.o: $(CBM_TOOLS_SRC_PATH)eyelidintegrator.cpp $(CBM_TOOLS_INCLUDE_PATH)/eyelidintegrator.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_TOOLS_INCLUDES) -o $(CBM_TOOLS_OBJ_PATH)eyelidintegrator.o $(CBM_TOOLS_SRC_PATH)eyelidintegrator.cpp

$(CBM_TOOLS_OBJ_PATH)poissonregencells.o: $(CBM_TOOLS_SRC_PATH)poissonregencells.cpp $(CBM_TOOLS_INCLUDE_PATH)/poissonregencells.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CBM_TOOLS_INCLUDES) -o $(CBM_TOOLS_OBJ_PATH)poissonregencells.o $(CBM_TOOLS_SRC_PATH)poissonregencells.cpp

####### CXX Tools Compiler Options

CXX_TOOLS_INCLUDES = -I. -I$(CXX_TOOLS_INCLUDE_PATH)

####### CXX Tools Build Rules

$(CXX_TOOLS_OBJ_PATH):
	@$(CHK_DIR_EXISTS) $(CXX_TOOLS_OBJ_PATH) || $(MKDIR) $(CXX_TOOLS_OBJ_PATH)

####### Compile CXX Tools Sources

$(CXX_TOOLS_OBJ_PATH)rawbytesrw.o: $(CXX_TOOLS_SRC_PATH)fileIO/rawbytesrw.cpp $(CXX_TOOLS_INCLUDE_PATH)fileIO/rawbytesrw.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CXX_TOOLS_INCLUDES) -o $(CXX_TOOLS_OBJ_PATH)rawbytesrw.o $(CXX_TOOLS_SRC_PATH)fileIO/rawbytesrw.cpp

$(CXX_TOOLS_OBJ_PATH)arrayvalidate.o: $(CXX_TOOLS_SRC_PATH)memoryMgmt/arrayvalidate.cpp $(CXX_TOOLS_INCLUDE_PATH)memoryMgmt/arrayvalidate.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CXX_TOOLS_INCLUDES) -o $(CXX_TOOLS_OBJ_PATH)arrayvalidate.o $(CXX_TOOLS_SRC_PATH)memoryMgmt/arrayvalidate.cpp

$(CXX_TOOLS_OBJ_PATH)dynamic2darray.o: $(CXX_TOOLS_SRC_PATH)memoryMgmt/dynamic2darray.cpp $(CXX_TOOLS_INCLUDE_PATH)memoryMgmt/dynamic2darray.h \
		                               $(CXX_TOOLS_INCLUDE_PATH)memoryMgmt/arrayvalidate.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CXX_TOOLS_INCLUDES) -o $(CXX_TOOLS_OBJ_PATH)dynamic2darray.o $(CXX_TOOLS_SRC_PATH)memoryMgmt/dynamic2darray.cpp

$(CXX_TOOLS_OBJ_PATH)mersenne.o: $(CXX_TOOLS_SRC_PATH)randGenerators/mersenne.cpp $(CXX_TOOLS_INCLUDE_PATH)randGenerators/randomc.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CXX_TOOLS_INCLUDES) -o $(CXX_TOOLS_OBJ_PATH)mersenne.o $(CXX_TOOLS_SRC_PATH)randGenerators/mersenne.cpp

$(CXX_TOOLS_OBJ_PATH)mother.o: $(CXX_TOOLS_SRC_PATH)randGenerators/mother.cpp $(CXX_TOOLS_INCLUDE_PATH)randGenerators/randomc.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CXX_TOOLS_INCLUDES) -o $(CXX_TOOLS_OBJ_PATH)mother.o $(CXX_TOOLS_SRC_PATH)randGenerators/mother.cpp

$(CXX_TOOLS_OBJ_PATH)sfmt.o: $(CXX_TOOLS_SRC_PATH)randGenerators/sfmt.cpp $(CXX_TOOLS_INCLUDE_PATH)randGenerators/sfmt.h \
		                     $(CXX_TOOLS_INCLUDE_PATH)randGenerators/randomc.h
	$(CXX) -c $(MODULE_CXX_FLAGS) $(CXX_TOOLS_INCLUDES) -o $(CXX_TOOLS_OBJ_PATH)sfmt.o $(CXX_TOOLS_SRC_PATH)randGenerators/sfmt.cpp


# ============================================ CLEAN UP ALL ======================================

clean: 
	rm -rf $(CBM_CORE_OBJ_PATH)  
	rm -rf $(CBM_DATA_OBJ_PATH)  
	rm -rf $(CBM_STATE_OBJ_PATH)  
	rm -rf $(CBM_TOOLS_OBJ_PATH)  
	rm -rf $(CXX_TOOLS_OBJ_PATH)  
	rm -rf $(BIG_SIM_OBJ_PATH)      

check: first

