#!/usr/bin/bash

declare -a base_name="untrained_bunny_tune_09262022"
declare -a sim_ext="sim"

declare -a build_file="build_file_tune_09262022.bld"
declare -a expt_file="practice_expt_file_3.expt"

declare -a command="cbm_sim"

declare -a in_bunny
declare -a out_bunny

# set -x # sets all commands to be echoed during script execution

if [[ -z "$1" ]]; then
	printf "[ERROR]: Number of bunnies not specified. You must provide a second\n"
	printf "[ERROR]: argument indicating the number of bunnies to be created.\n"
	printf "[ERROR]: Exiting...\n"
	exit 1
fi

printf "[INFO]: Entering build directory...\n"
cd ../build/

printf "[INFO]: Constructing $1 bunnies...\n\n"
for (( i=1; i<=$1; i++)); do
	printf "[INFO]: Generating bunny number $i...\n"
	./"$command" "$build_file" "${base_name}_${i}.${sim_ext}"
	printf "[INFO]: Finished generating bunny number $i.\n"
done
printf "\n[INFO]: Finished constructing $1 bunnies.\n"

# printf "\n[INFO]: daisy chaining bunny 1 on experiment file ${expt_file} 5 times.\n"
# in_bunny="${base_name}_1.${sim_ext}"
# for i in {1..5}; do
# 	printf "\n[INFO]: Experiment Run Counter: ${i}\n\n"
# 	out_bunny="${base_name}_1_${i}.${sim_ext}"
# 	# printf "[INFO]: Input file:  ${in_bunny}\n"
# 	# printf "[INFO]: Output file: ${out_bunny}\n"
# 	./big_sim "$expt_file" "$in_bunny" "$out_bunny"
# 	in_bunny=$out_bunny
# done
# printf "[INFO]: Finished daisy chaining bunny 1 on experiment file 5 times.\n"
 
printf "[INFO]: Exiting build directory...\n"
cd ../scripts
printf "[INFO]: Back in scripts/ directory. Exiting successfully...\n"

